---
title: "Detroit Metro Land Cover Change Modeled by Cellular Automata"
author: "K. Arthur Endsley"
date: 'Sunday, November 23, 2014'
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r preamble, warning=FALSE, message=FALSE, results=FALSE}
library(sp, raster)
library(rgdal)
library(plyr, reshape2)
library(bnlearn)

setwd('/usr/local/dev/rdetroit/')
options(stringsAsFactors=FALSE)
```

# Preparation

## Land Cover Data

We'll try aggregating the data to 90 meters to see if that gives us a feasible grid with which to work.

```{r}
file.loc <- '/home/arthur/Workspace/TermProject/'

require(raster)
rast2000 <- raster::raster(paste0(file.loc, 'nlcd2001_nad83.tif'))
rast2006 <- raster::raster(paste0(file.loc, 'nlcd2006_nad83.tif'))
reclass.matrix <- matrix(c(c(0,10,0), c(10,11,NA), c(12,20,0),
                           c(20,23,1), c(23,24,2), c(24,99,0)),
                         byrow=TRUE, ncol=3)
dev2001 <- raster::reclassify(rast2000, reclass.matrix, right=TRUE) # Intervals closed on right
dev2006 <- raster::reclassify(rast2006, reclass.matrix, right=TRUE)
```

```{r}
counties <- readOGR(paste0(file.loc, 'ancillary/co26_d00_select_nad83.shp'),
                    'co26_d00_select_nad83')
counties <- spTransform(counties, crs(dev2000))

plot(counties, col='#EEEEEE')
plot(dev2006 - dev2001, breaks=c(-2, -1, 0, 2), add=TRUE,
     col=c('#77DD00', '#FFFFFF00', '#113355'))
title('Change in Metro Detroit Development, 2001-2006')
```

We'll first aggregate the land cover data to 300 meters.

```{r}
dev2001 <- aggregate(dev2001, fact=10, fun=modal)
dev2006 <- aggregate(dev2006, fact=10, fun=modal)
save(dev2001, dev2006, file='rda/caAggregates.rda')
```

```{r}
```

